# Generated by Django 6.0.5 on 2026-06-05 01:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loyaltee", "0002_compraitem_recompensasreclamadas"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Categoria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=200, unique=True)),
                ("descripcion", models.TextField(blank=True, default="")),
                ("icono", models.CharField(blank=True, default="", max_length=100)),
                ("activa", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Categoría",
                "verbose_name_plural": "Categorías",
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="Devolucion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "motivo",
                    models.CharField(
                        choices=[
                            ("defectuoso", "Producto Defectuoso"),
                            ("no_coincide", "No Coincide con la Descripción"),
                            ("cambio_idea", "Cambio de Idea"),
                            ("talla_incorrecta", "Talla Incorrecta"),
                            ("daño_envio", "Dañado en el Envío"),
                            ("otro", "Otro"),
                        ],
                        max_length=30,
                    ),
                ),
                ("descripcion", models.TextField()),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("solicitada", "Solicitada"),
                            ("aprobada", "Aprobada"),
                            ("rechazada", "Rechazada"),
                            ("en_transito", "En Tránsito"),
                            ("recibida", "Recibida"),
                            ("procesada", "Procesada"),
                            ("cancelada", "Cancelada"),
                        ],
                        default="solicitada",
                        max_length=20,
                    ),
                ),
                (
                    "monto_reembolso",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("puntos_recuperados", models.PositiveIntegerField(default=0)),
                ("fecha_solicitud", models.DateTimeField(auto_now_add=True)),
                ("fecha_aprobacion", models.DateTimeField(blank=True, null=True)),
                ("fecha_recepcion", models.DateTimeField(blank=True, null=True)),
                ("notas_admin", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "compra",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="devoluciones",
                        to="loyaltee.compra",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="devoluciones",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Devolución",
                "verbose_name_plural": "Devoluciones",
                "ordering": ["-fecha_solicitud"],
            },
        ),
        migrations.CreateModel(
            name="Producto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=200)),
                ("descripcion", models.TextField(blank=True, default="")),
                ("precio", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "precio_descuento",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("stock", models.PositiveIntegerField(default=0)),
                ("sku", models.CharField(max_length=100, unique=True)),
                ("marca", models.CharField(blank=True, default="", max_length=100)),
                ("talla", models.CharField(blank=True, default="", max_length=50)),
                ("color", models.CharField(blank=True, default="", max_length=100)),
                ("puntos_otorgados", models.PositiveIntegerField(default=0)),
                ("activo", models.BooleanField(default=True)),
                ("destacado", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "categoria",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="productos",
                        to="loyaltee.categoria",
                    ),
                ),
            ],
            options={
                "verbose_name": "Producto",
                "verbose_name_plural": "Productos",
                "ordering": ["-destacado", "nombre"],
            },
        ),
    ]
